project:
  type: website

website:
  title: "Abbie's AI Tutorials"
  site-url: "https://apetulante.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/apetulante
      - icon: linkedin
        href: https://www.linkedin.com/in/apetulante/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
